
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibmV3dGVzdCIsImlhdCI6MTcwMTY0OTEwOSwiZXhwIjoxNzAxNjQ5MTI5fQ.VRw0RbWgDpxAvkCYhKROZRYJBrIk-mldlp2CgCXxnMg
### 

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "newtest",
    "password": "1"
}


###

POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTZiZDA3ODNlODEyYzU0Y2RhNGVkY2IiLCJ1c2VybmFtZSI6Im5ld3Rlc3QiLCJwYXNzd29yZCI6IiQyYiQxMCQ2SjJtMkVrbG45SnJSWUs3d3RJNDN1clRHQU1YVzIyMkhjOXFRMi9kR2RMaU1DOTRxVDRSaSIsImlzQmxvZ2dlciI6ZmFsc2UsIl9fdiI6MCwiaWF0IjoxNzAxNjQ4NDk5fQ.1IpmQw-L4P50Q0_OrKtwycCduJfFfr99mCrPzmojkZE"
}